type = "checkout_ui_extension"
name = "example-checkout--product-offer-pre-purchase--js"

# [START product-offer-pre-purchase.ext-config]
extension_points = [
  'Checkout::Dynamic::Render'
]
# [END product-offer-pre-purchase.ext-config]

# [START product-offer-pre-purchase.api-access]
[capabilities]
api_access = true
# [END product-offer-pre-purchase.api-access]
