# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-04"

[[extensions]]
type = "ui_extension"
name = "pre-purchase-offer"
handle = "pre-purchase-offer"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview
# [START product-offer-pre-purchase.ext-config]
[[extensions.targeting]]
module = "./src/Checkout.js"
target = "purchase.checkout.block.render"
# [END product-offer-pre-purchase.ext-config]
# [START product-offer-pre-purchase.api-access]
[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true
# [END product-offer-pre-purchase.api-access]
